// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat-group.proto

package chatgroup

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_MessageType int32

const (
	// messages to handle subscriptions at the publishing service
	Message_SUBSCRIBE_REQUEST Message_MessageType = 0
	Message_SUBSCRIBE_REPLY   Message_MessageType = 1
	// messages to handle unsubscriptions at the publishing service
	Message_UNSUBSCRIBE_REQUEST Message_MessageType = 2
	Message_UNSUBSCRIBE_REPLY   Message_MessageType = 3
	// messages to publish chat messages via the publishing service
	Message_PUBLISH_REQUEST Message_MessageType = 4
	Message_PUBLISH_REPLY   Message_MessageType = 5
)

var Message_MessageType_name = map[int32]string{
	0: "SUBSCRIBE_REQUEST",
	1: "SUBSCRIBE_REPLY",
	2: "UNSUBSCRIBE_REQUEST",
	3: "UNSUBSCRIBE_REPLY",
	4: "PUBLISH_REQUEST",
	5: "PUBLISH_REPLY",
}
var Message_MessageType_value = map[string]int32{
	"SUBSCRIBE_REQUEST":   0,
	"SUBSCRIBE_REPLY":     1,
	"UNSUBSCRIBE_REQUEST": 2,
	"UNSUBSCRIBE_REPLY":   3,
	"PUBLISH_REQUEST":     4,
	"PUBLISH_REPLY":       5,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_5bd7bf8611bdbc77, []int{2, 0}
}

type Member struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Leader               bool     `protobuf:"varint,4,opt,name=leader" json:"leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_5bd7bf8611bdbc77, []int{0}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Member) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Member) GetLeader() bool {
	if m != nil {
		return m.Leader
	}
	return false
}

type MemberList struct {
	Member               []*Member `protobuf:"bytes,1,rep,name=member" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberList) Reset()         { *m = MemberList{} }
func (m *MemberList) String() string { return proto.CompactTextString(m) }
func (*MemberList) ProtoMessage()    {}
func (*MemberList) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_5bd7bf8611bdbc77, []int{1}
}
func (m *MemberList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberList.Unmarshal(m, b)
}
func (m *MemberList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberList.Marshal(b, m, deterministic)
}
func (dst *MemberList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberList.Merge(dst, src)
}
func (m *MemberList) XXX_Size() int {
	return xxx_messageInfo_MemberList.Size(m)
}
func (m *MemberList) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberList.DiscardUnknown(m)
}

var xxx_messageInfo_MemberList proto.InternalMessageInfo

func (m *MemberList) GetMember() []*Member {
	if m != nil {
		return m.Member
	}
	return nil
}

// Services are mapped by request/reply message types
type Message struct {
	MsgType              Message_MessageType `protobuf:"varint,1,opt,name=msgType,enum=chatgroup.Message_MessageType" json:"msgType,omitempty"`
	Sender               *Member             `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	Text                 string              `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	MemberList           *MemberList         `protobuf:"bytes,4,opt,name=memberList" json:"memberList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_group_5bd7bf8611bdbc77, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgType() Message_MessageType {
	if m != nil {
		return m.MsgType
	}
	return Message_SUBSCRIBE_REQUEST
}

func (m *Message) GetSender() *Member {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetMemberList() *MemberList {
	if m != nil {
		return m.MemberList
	}
	return nil
}

func init() {
	proto.RegisterType((*Member)(nil), "chatgroup.Member")
	proto.RegisterType((*MemberList)(nil), "chatgroup.MemberList")
	proto.RegisterType((*Message)(nil), "chatgroup.Message")
	proto.RegisterEnum("chatgroup.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

func init() { proto.RegisterFile("chat-group.proto", fileDescriptor_chat_group_5bd7bf8611bdbc77) }

var fileDescriptor_chat_group_5bd7bf8611bdbc77 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0xbb, 0x40,
	0x10, 0xc6, 0xff, 0x4b, 0xfb, 0xa7, 0x76, 0x1a, 0x6b, 0x3b, 0x4d, 0x95, 0x93, 0x21, 0x9c, 0xf0,
	0x20, 0x07, 0x8c, 0xd1, 0x33, 0x86, 0xc4, 0x26, 0xd4, 0xd4, 0xa5, 0x24, 0x7a, 0x32, 0x54, 0x37,
	0x48, 0x22, 0x65, 0x03, 0x98, 0xe8, 0x63, 0xf8, 0x60, 0xbe, 0x93, 0x99, 0xa5, 0x45, 0x9a, 0x7a,
	0x62, 0xe6, 0x9b, 0x1f, 0xdf, 0x7c, 0x93, 0x85, 0xd1, 0xf3, 0x6b, 0x5c, 0x9d, 0x27, 0x45, 0xfe,
	0x2e, 0x1d, 0x59, 0xe4, 0x55, 0x8e, 0x7d, 0x52, 0x94, 0x60, 0x3d, 0x80, 0x3e, 0x17, 0xd9, 0x4a,
	0x14, 0x88, 0xd0, 0x5d, 0xc7, 0x99, 0x30, 0x98, 0xc9, 0xec, 0x3e, 0x57, 0x35, 0x0e, 0x41, 0x4b,
	0xa5, 0xa1, 0x29, 0x45, 0x4b, 0x25, 0x31, 0x32, 0x2f, 0x2a, 0xa3, 0x53, 0x33, 0x54, 0xe3, 0x31,
	0xe8, 0x6f, 0x22, 0x7e, 0x11, 0x85, 0xd1, 0x35, 0x99, 0x7d, 0xc0, 0x37, 0x9d, 0x75, 0x05, 0x50,
	0x3b, 0x07, 0x69, 0x59, 0xe1, 0x19, 0xe8, 0x99, 0xea, 0x0c, 0x66, 0x76, 0xec, 0x81, 0x3b, 0x76,
	0x9a, 0x0c, 0x4e, 0x8d, 0xf1, 0x0d, 0x60, 0x7d, 0x6b, 0xd0, 0x9b, 0x8b, 0xb2, 0x8c, 0x13, 0x81,
	0xd7, 0xd0, 0xcb, 0xca, 0x64, 0xf9, 0x29, 0xeb, 0x5c, 0x43, 0xf7, 0x74, 0xe7, 0x3f, 0x05, 0x6d,
	0xbf, 0x44, 0xf1, 0x2d, 0x4e, 0x0b, 0x4b, 0xb1, 0xa6, 0x58, 0x14, 0xff, 0xef, 0x85, 0x35, 0x40,
	0x57, 0x55, 0xe2, 0xa3, 0xb9, 0x8a, 0x6a, 0xbc, 0x04, 0xc8, 0x9a, 0xf4, 0xea, 0xb2, 0x81, 0x3b,
	0xdd, 0xb3, 0xa0, 0x21, 0x6f, 0x81, 0xd6, 0x17, 0x83, 0x41, 0x2b, 0x0e, 0x4e, 0x61, 0x1c, 0x46,
	0x5e, 0x78, 0xc3, 0x67, 0x9e, 0xff, 0xc4, 0xfd, 0xfb, 0xc8, 0x0f, 0x97, 0xa3, 0x7f, 0x38, 0x81,
	0xa3, 0xb6, 0xbc, 0x08, 0x1e, 0x47, 0x0c, 0x4f, 0x60, 0x12, 0xdd, 0xed, 0xd3, 0x1a, 0x99, 0xec,
	0x0e, 0x88, 0xef, 0x90, 0xc9, 0x22, 0xf2, 0x82, 0x59, 0x78, 0xdb, 0xb0, 0x5d, 0x1c, 0xc3, 0xe1,
	0xaf, 0x48, 0xdc, 0xff, 0x95, 0xae, 0x1e, 0xfd, 0xe2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x01, 0x66,
	0xd5, 0xcf, 0x08, 0x02, 0x00, 0x00,
}
