// Code generated by protoc-gen-go. DO NOT EDIT.
// source: servicelist.proto

package serviceproviders

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Service_Status int32

const (
	Service_CANDIDATE Service_Status = 0
	Service_SERVICE   Service_Status = 1
	Service_PROVIDER  Service_Status = 2
	Service_NOTFOUND  Service_Status = 3
)

var Service_Status_name = map[int32]string{
	0: "CANDIDATE",
	1: "SERVICE",
	2: "PROVIDER",
	3: "NOTFOUND",
}
var Service_Status_value = map[string]int32{
	"CANDIDATE": 0,
	"SERVICE":   1,
	"PROVIDER":  2,
	"NOTFOUND":  3,
}

func (x Service_Status) String() string {
	return proto.EnumName(Service_Status_name, int32(x))
}
func (Service_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_servicelist_0be05ad3771145e9, []int{0, 0}
}

type Message_MessageType int32

const (
	// messages to get a service from a provider
	Message_SERVICE_REQUEST Message_MessageType = 0
	Message_SERVICE_REPLY   Message_MessageType = 1
)

var Message_MessageType_name = map[int32]string{
	0: "SERVICE_REQUEST",
	1: "SERVICE_REPLY",
}
var Message_MessageType_value = map[string]int32{
	"SERVICE_REQUEST": 0,
	"SERVICE_REPLY":   1,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_servicelist_0be05ad3771145e9, []int{2, 0}
}

type Service struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip                   string         `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port                 string         `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Status               Service_Status `protobuf:"varint,4,opt,name=status,enum=serviceproviders.Service_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_servicelist_0be05ad3771145e9, []int{0}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Service) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Service) GetStatus() Service_Status {
	if m != nil {
		return m.Status
	}
	return Service_CANDIDATE
}

// A service provider administrates a list of service candidates (with one working service)
type ServiceProvider struct {
	Provider             *Service   `protobuf:"bytes,1,opt,name=provider" json:"provider,omitempty"`
	Services             []*Service `protobuf:"bytes,2,rep,name=services" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceProvider) Reset()         { *m = ServiceProvider{} }
func (m *ServiceProvider) String() string { return proto.CompactTextString(m) }
func (*ServiceProvider) ProtoMessage()    {}
func (*ServiceProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_servicelist_0be05ad3771145e9, []int{1}
}
func (m *ServiceProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceProvider.Unmarshal(m, b)
}
func (m *ServiceProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceProvider.Marshal(b, m, deterministic)
}
func (dst *ServiceProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceProvider.Merge(dst, src)
}
func (m *ServiceProvider) XXX_Size() int {
	return xxx_messageInfo_ServiceProvider.Size(m)
}
func (m *ServiceProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceProvider.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceProvider proto.InternalMessageInfo

func (m *ServiceProvider) GetProvider() *Service {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *ServiceProvider) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

// Mappings by request/reply message types
type Message struct {
	MsgType              Message_MessageType `protobuf:"varint,1,opt,name=msgType,enum=serviceproviders.Message_MessageType" json:"msgType,omitempty"`
	ServiceProvider      *ServiceProvider    `protobuf:"bytes,2,opt,name=serviceProvider" json:"serviceProvider,omitempty"`
	Sender               *Service            `protobuf:"bytes,3,opt,name=sender" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_servicelist_0be05ad3771145e9, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgType() Message_MessageType {
	if m != nil {
		return m.MsgType
	}
	return Message_SERVICE_REQUEST
}

func (m *Message) GetServiceProvider() *ServiceProvider {
	if m != nil {
		return m.ServiceProvider
	}
	return nil
}

func (m *Message) GetSender() *Service {
	if m != nil {
		return m.Sender
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "serviceproviders.Service")
	proto.RegisterType((*ServiceProvider)(nil), "serviceproviders.ServiceProvider")
	proto.RegisterType((*Message)(nil), "serviceproviders.Message")
	proto.RegisterEnum("serviceproviders.Service_Status", Service_Status_name, Service_Status_value)
	proto.RegisterEnum("serviceproviders.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

func init() { proto.RegisterFile("servicelist.proto", fileDescriptor_servicelist_0be05ad3771145e9) }

var fileDescriptor_servicelist_0be05ad3771145e9 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0xa4, 0x24, 0xed, 0xc4, 0xb6, 0xdb, 0xf1, 0x12, 0x6f, 0x31, 0x20, 0xf4, 0x14,
	0x30, 0x52, 0xf0, 0xa6, 0xa5, 0x89, 0x50, 0xd4, 0xb6, 0x6e, 0xd2, 0x82, 0x27, 0xa9, 0xba, 0x94,
	0x80, 0x6d, 0x42, 0x36, 0x16, 0x3c, 0x89, 0x1f, 0xcc, 0xef, 0x26, 0xd9, 0x6c, 0xfc, 0x53, 0x29,
	0x3d, 0x65, 0xf2, 0xf8, 0xbd, 0x79, 0x33, 0x93, 0x40, 0x97, 0xb3, 0x6c, 0x13, 0x3f, 0xb1, 0x97,
	0x98, 0xe7, 0x6e, 0x9a, 0x25, 0x79, 0x82, 0x44, 0x4a, 0x69, 0x96, 0x6c, 0xe2, 0x67, 0x96, 0x71,
	0xe7, 0x53, 0x01, 0x23, 0x2c, 0x45, 0x44, 0xa8, 0xaf, 0x17, 0x2b, 0x66, 0x29, 0xb6, 0xd2, 0x6b,
	0x52, 0x51, 0x63, 0x1b, 0xd4, 0x38, 0xb5, 0x54, 0xa1, 0xa8, 0x71, 0x5a, 0x30, 0x69, 0x92, 0xe5,
	0x96, 0x56, 0x32, 0x45, 0x8d, 0xe7, 0xa0, 0xf3, 0x7c, 0x91, 0xbf, 0x72, 0xab, 0x6e, 0x2b, 0xbd,
	0xb6, 0x67, 0xbb, 0xdb, 0x31, 0xae, 0x8c, 0x70, 0x43, 0xc1, 0x51, 0xc9, 0x3b, 0x97, 0xa0, 0x97,
	0x0a, 0xb6, 0xa0, 0x39, 0x1c, 0x8c, 0xfd, 0x91, 0x3f, 0x88, 0x02, 0x52, 0x43, 0x13, 0x8c, 0x30,
	0xa0, 0xf3, 0xd1, 0x30, 0x20, 0x0a, 0x1e, 0x40, 0x63, 0x4a, 0x27, 0xf3, 0x91, 0x1f, 0x50, 0xa2,
	0x16, 0x6f, 0xe3, 0x49, 0x74, 0x35, 0x99, 0x8d, 0x7d, 0xa2, 0x39, 0xef, 0xd0, 0x91, 0xbd, 0xa7,
	0x32, 0x0c, 0xfb, 0xd0, 0xa8, 0x82, 0xc5, 0x2a, 0xa6, 0x77, 0xb4, 0x73, 0x20, 0xfa, 0x8d, 0x16,
	0x36, 0x49, 0x71, 0x4b, 0xb5, 0xb5, 0x3d, 0xb6, 0x0a, 0x75, 0x3e, 0x54, 0x30, 0x6e, 0x19, 0xe7,
	0x8b, 0x25, 0xc3, 0x0b, 0x30, 0x56, 0x7c, 0x19, 0xbd, 0xa5, 0xe5, 0x0d, 0xdb, 0xde, 0xc9, 0xff,
	0x0e, 0x92, 0xad, 0x9e, 0x05, 0x4c, 0x2b, 0x17, 0x5e, 0x43, 0x87, 0xff, 0xdd, 0x46, 0x9c, 0xde,
	0xf4, 0x8e, 0x77, 0x8e, 0x52, 0x81, 0x74, 0xdb, 0x89, 0xa7, 0xa0, 0x73, 0xb6, 0x2e, 0x7a, 0x68,
	0xfb, 0xae, 0x20, 0x41, 0xa7, 0x0f, 0xe6, 0xaf, 0xb9, 0xf0, 0x10, 0x3a, 0xf2, 0x2b, 0x3c, 0xd0,
	0xe0, 0x6e, 0x16, 0x84, 0x11, 0xa9, 0x61, 0x17, 0x5a, 0x3f, 0xe2, 0xf4, 0xe6, 0x9e, 0x28, 0x8f,
	0xba, 0xf8, 0xbb, 0xce, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x95, 0xf1, 0x47, 0x72, 0x02,
	0x00, 0x00,
}
